import fs from "node:fs"

const lines = []
const L = (...args) => lines.push(args.map((a) => (a == null ? "" : String(a))).join(""))

L(`import { useState, useEffect } from "react"`)
L(`import { loadState, saveState } from "./storage"`)
L()
L(`type Tab = "schedule" | "fund" | "thongke" | "members" | "history"`)
L()
L(`type PlayerMatchStat = {`)
L(`  playerName: string`)
L(`  position: string`)
L(`  minutesPlayed: number`)
L(`  goals: number`)
L(`  assists: number`)
L(`  passesSuccess: number`)
L(`  passesAttempted: number`)
L(`  tackles: number`)
L(`  shotsOnTarget: number`)
L(`  interceptions: number`)
L(`  saves: number`)
L(`  keyPasses: number`)
L(`  dribbles: number`)
L(`  clearances: number`)
L(`  ballRecoveries: number`)
L(`  penaltySaved: number`)
L(`  penaltyMissed: number`)
L(`  ownGoal: number`)
L(`  yellowCard: boolean`)
L(`  redCard: boolean`)
L(`  rating: number`)
L(`}`)
L()
L(`type HistoryMatch = {`)
L(`  id: number`)
L(`  date: string`)
L(`  opponent: string`)
L(`  venue: string`)
L(`  type: string`)
L(`  scoreUs: number`)
L(`  scoreThem: number`)
L(`  lineup: string[]`)
L(`  playerStats: PlayerMatchStat[]`)
L(`}`)
L()
L(`type EntryStep = "result" | "lineup" | "stats" | "review"`)
L()
L(`type Member = {`)
L(`  id: number`)
L(`  name: string`)
L(`  position: string`)
L(`  joinDate: string`)
L(`}`)
L()
L(`type FundTransaction = {`)
L(`  id: number`)
L(`  date: string`)
L(`  type: "in" | "out"`)
L(`  member: string`)
L(`  desc: string`)
L(`  amount: number`)
L(`}`)
L()
L(`type MatchResult = { us: number; them: number }`)
L()
L(`const POS_GROUP: Record<string, "GK" | "DEF" | "MID" | "ATT"> = {`)
L(`  GK: "GK", CB: "DEF", LB: "DEF", RB: "DEF",`)
L(`  CDM: "MID", CM: "MID", CAM: "MID", LM: "MID", RM: "MID",`)
L(`  LW: "ATT", RW: "ATT", ST: "ATT", CF: "ATT",`)
L(`}`)
L()
L(`function calcRating(s: Omit<PlayerMatchStat, "rating">, m: MatchResult): number {`)
L(`  const g = POS_GROUP[s.position] ?? "MID"`)
L(`  const accPct =`)
L(`    (s.passesAttempted ?? 0) > 0`)
L(`      ? (s.passesSuccess / (s.passesAttempted ?? 0)) * 100`)
L(`      : null`)
L(`  const accBonus =`)
L(`    accPct == null`)
L(`      ? 0`)
L(`      : accPct >= 85`)
L(`        ? 0.2`)
L(`        : accPct >= 75`)
L(`          ? 0.1`)
L(`          : accPct >= 60`)
L(`            ? 0`)
L(`            : -0.2`)
L(`  const goalW = { GK: 1.4, DEF: 1.4, MID: 1.0, ATT: 0.6 }[g]`)
L(`  const assistW = { GK: 1.2, DEF: 1.2, MID: 0.8, ATT: 0.55 }[g]`)
L(`  const cleanSheetW = { GK: 0.5, DEF: 0.35, MID: 0.15, ATT: 0.1 }[g]`)
L(`  const contrib =`)
L(`    s.minutesPlayed * 0.002 +`)
L(`    s.goals * goalW +`)
L(`    s.assists * assistW +`)
L(`    s.shotsOnTarget * 0.07 +`)
L(`    s.tackles * 0.06 +`)
L(`    s.interceptions * 0.06 +`)
L(`    s.saves * 0.06 +`)
L(`    s.passesSuccess * 0.0025 +`)
L(`    (s.keyPasses ?? 0) * 0.1 +`)
L(`    (s.dribbles ?? 0) * 0.1 +`)
L(`    (s.clearances ?? 0) * 0.025 +`)
L(`    (s.ballRecoveries ?? 0) * 0.025 +`)
L(`    (s.penaltySaved ?? 0) * 1.0`)
L(`  const minFactor = 0.4 + 0.6 * Math.min(1, s.minutesPlayed / 90)`)
L(`  let total = 5.9 + contrib * minFactor + accBonus`)
L(`  if (m.them === 0) total += cleanSheetW`)
L(`  if ((g === "GK" || g === "DEF") && m.them >= 3) total -= 0.25 * (m.them - 2)`)
L(`  if (m.us > m.them) total += 0.1`)
L(`  if (m.us < m.them) total -= 0.15`)
L(`  total -= (s.yellowCard ? 1 : 0) * 0.35`)
L(`  total -= (s.redCard ? 1 : 0) * 1.2`)
L(`  total -= (s.penaltyMissed ?? 0) * 0.8`)
L(`  total -= (s.ownGoal ?? 0) * 2.0`)
L(`  return Math.min(10, Math.max(1, Math.round(total * 10) / 10))`)
L(`}`)
L()
L(`function RatingColor(r: number) {`)
L(`  if (r >= 8) return "#a3e635"`)
L(`  if (r >= 7) return "#fbbf24"`)
L(`  return "#94a3b8"`)
L(`}`)
L()
L(`function formatCurrency(n: number) {`)
L(`  return n.toLocaleString("vi-VN") + " ₫"`)
L(`}`)
L()
L(`function PosBadge({ pos }: { pos: string }) {`)
L(`  const colors: Record<string, string> = {`)
L(`    GK: "#fbbf24", CB: "#38bdf8", LB: "#38bdf8", RB: "#38bdf8",`)
L(`    CDM: "#a78bfa", CM: "#a78bfa", CAM: "#a78bfa", LM: "#a78bfa", RM: "#a78bfa",`)
L(`    LW: "#f472b6", RW: "#f472b6", ST: "#f472b6", CF: "#f472b6",`)
L(`  }`)
L(`  const c = colors[pos] ?? "#6b7fa0"`)
L(`  return (`)
L(`    <span`)
L(`      style={{`)
L(`        display: "inline-block",`)
L(`        background: c + "22",`)
L(`        color: c,`)
L(`        borderRadius: "4px",`)
L(`        padding: "2px 8px",`)
L(`        fontFamily: "'JetBrains Mono', monospace",`)
L(`        fontSize: "10px",`)
L(`        fontWeight: 600,`)
L(`        letterSpacing: "0.06em",`)
L(`      }}`)
L(`    >`)
L(`      {pos}`)
L(`    </span>`)
L(`  )`)
L(`}`)

fs.writeFileSync("src/App.tsx", lines.join("\n") + "\n", "utf8")
console.log("Part 1 written:", lines.length, "lines")