import fs from "node:fs"

const lines = []
const L = (...args) => lines.push(args.map((a) => (a == null ? "" : String(a))).join(""))

L("const TEAM_NAME = \"FC Rồng Vàng\"")
L("const TEAM_FUND = 4_850_000")
L()
L("const upcomingMatches = [")
L("  { id: 1, opponent: \"Sao Đỏ FC\", date: \"2026-08-16\", time: \"18:00\", venue: \"Sân vận động Quân khu 7\", type: \"Giải hạng Nhất\", votes: 6, totalMembers: 18, home: true },")
L("  { id: 2, opponent: \"Ngôi Sao Xanh\", date: \"2026-08-23\", time: \"17:00\", venue: \"Sân Tân Bình, Q.Tân Bình, TP.HCM\", type: \"Giao hữu\", votes: 4, totalMembers: 18, home: false },")
L("]")
L()
L("const DEFAULT_FUND_TRANSACTIONS: FundTransaction[] = [")
L("  { id: 1, date: \"2026-08-01\", type: \"in\", member: \"Nguyễn Văn Hùng\", desc: \"Quỹ tháng 8\", amount: 200_000 },")
L("  { id: 2, date: \"2026-08-01\", type: \"in\", member: \"Trần Minh Tuấn\", desc: \"Quỹ tháng 8\", amount: 200_000 },")
L("  { id: 3, date: \"2026-08-01\", type: \"in\", member: \"Lê Quốc Bảo\", desc: \"Quỹ tháng 8\", amount: 200_000 },")
L("  { id: 4, date: \"2026-08-02\", type: \"out\", member: \"\", desc: \"Thuê sân Thống Nhất\", amount: -350_000 },")
L("  { id: 5, date: \"2026-08-03\", type: \"in\", member: \"Phạm Đức Anh\", desc: \"Quỹ tháng 8\", amount: 200_000 },")
L("  { id: 6, date: \"2026-08-05\", type: \"out\", member: \"\", desc: \"Mua bóng tập (x2)\", amount: -480_000 },")
L("  { id: 7, date: \"2026-08-07\", type: \"in\", member: \"Võ Thanh Long\", desc: \"Quỹ tháng 8 + đóng bù T7\", amount: 400_000 },")
L("  { id: 8, date: \"2026-08-08\", type: \"in\", member: \"Đinh Hoàng Nam\", desc: \"Quỹ tháng 8\", amount: 200_000 },")
L("  { id: 9, date: \"2026-08-09\", type: \"out\", member: \"\", desc: \"Nước uống trận giao hữu\", amount: -120_000 },")
L("  { id: 10, date: \"2026-08-10\", type: \"in\", member: \"Hoàng Đình Khải\", desc: \"Quỹ tháng 8\", amount: 200_000 },")
L("]")
L()
L("const players = [")
L("  { id: 1, name: \"Nguyễn Văn Hùng\", position: \"GK\", matches: 12, goals: 0, assists: 1, yellowCards: 0, redCards: 0, rating: 7.8, attendance: 92 },")
L("  { id: 2, name: \"Trần Minh Tuấn\", position: \"CB\", matches: 11, goals: 2, assists: 1, yellowCards: 2, redCards: 0, rating: 7.4, attendance: 85 },")
L("  { id: 3, name: \"Lê Quốc Bảo\", position: \"CB\", matches: 10, goals: 1, assists: 0, yellowCards: 1, redCards: 0, rating: 7.1, attendance: 77 },")
L("  { id: 4, name: \"Phạm Đức Anh\", position: \"LB\", matches: 12, goals: 0, assists: 3, yellowCards: 1, redCards: 0, rating: 7.6, attendance: 92 },")
L("  { id: 5, name: \"Võ Thanh Long\", position: \"RB\", matches: 9, goals: 1, assists: 2, yellowCards: 3, redCards: 1, rating: 6.8, attendance: 69 },")
L("  { id: 6, name: \"Đinh Hoàng Nam\", position: \"CM\", matches: 12, goals: 4, assists: 5, yellowCards: 1, redCards: 0, rating: 8.2, attendance: 92 },")
L("  { id: 7, name: \"Hoàng Đình Khải\", position: \"CM\", matches: 11, goals: 3, assists: 4, yellowCards: 2, redCards: 0, rating: 7.9, attendance: 85 },")
L("  { id: 8, name: \"Bùi Quang Huy\", position: \"CAM\", matches: 10, goals: 5, assists: 6, yellowCards: 0, redCards: 0, rating: 8.5, attendance: 77 },")
L("  { id: 9, name: \"Ngô Sơn Tùng\", position: \"LW\", matches: 11, goals: 6, assists: 3, yellowCards: 1, redCards: 0, rating: 8.1, attendance: 85 },")
L("  { id: 10, name: \"Dương Văn Kiên\", position: \"RW\", matches: 10, goals: 4, assists: 5, yellowCards: 0, redCards: 0, rating: 8.0, attendance: 77 },")
L("  { id: 11, name: \"Lý Công Vinh Jr.\", position: \"ST\", matches: 12, goals: 11, assists: 2, yellowCards: 1, redCards: 0, rating: 8.7, attendance: 92 },")
L("  { id: 12, name: \"Trịnh Thế Bảo\", position: \"ST\", matches: 8, goals: 5, assists: 1, yellowCards: 2, redCards: 0, rating: 7.5, attendance: 62 },")
L("]")
L()
L("const ALL_PLAYER_NAMES = players.map((p) => ({ name: p.name, position: p.position }))")
L()
L("const DEFAULT_MEMBERS: Member[] = players.map((p, i) => ({")
L("  id: i + 1, name: p.name, position: p.position, joinDate: \"2026-01-01\",")
L("}))")

fs.writeFileSync("src/App.tsx", lines.join("\n") + "\n", "utf8")
console.log("Part 2 written:", lines.length, "lines")